import { Switch } from "@/components/common/ui/switch";

export const PRODUCT_LIST_DATA = [
  {
    id: 1,
    logo: "/images/brand-logo/plurk.png",
    name: "Necklaces",
    status: "Active",
    no_of_products: "45/50",
    budget_used: "33L",
    margin: "10%",
    last_updated: "2 min ago",
  },
  {
    id: 2,
    logo: "/images/brand-logo/disqus.png",
    name: "Bracelets",
    status: "Active",
    no_of_products: "35/55",
    budget_used: "33L",
    margin: "10%-12%",
    last_updated: "3 min ago",
  },
  {
    id: 3,
    logo: "/images/brand-logo/clara.png",
    name: "Rings",
    status: "Active",
    no_of_products: "30/57",
    budget_used: "32L",
    margin: "9%",
    last_updated: "5 min ago",
  },
  {
    id: 4,
    logo: "/images/brand-logo/vimeo.png",
    name: "Earrings",
    status: "Active",
    no_of_products: "30/35",
    budget_used: "25L",
    margin: "15%",
    last_updated: "1 min ago",
  },
  {
    id: 5,
    logo: "/images/brand-logo/vimeo.png",
    name: "Wedding Bands",
    status: "Active",
    no_of_products: "25/30",
    budget_used: "15L",
    margin: "7%",
    last_updated: "7 min ago",
  },
  {
    id: 6,
    logo: "/images/brand-logo/spring.png",
    name: "Mangalsutra",
    status: "Active",
    no_of_products: "26/40",
    budget_used: "33L",
    margin: "7%-10%",
    last_updated: "3 min ago",
  },
  {
    id: 7,
    logo: "/images/brand-logo/spring.png",
    name: "Pendants",
    status: "Inactive",
    no_of_products: "15/30",
    budget_used: "28L",
    margin: "11%",
    last_updated: "8 min ago",
  },
];

export const PRODUCT_MASTER_DATA = [
  {
    id: 1,
    productImg: "/images/products/product-ring.png",
    designNo: "1101-01PRI",
    category: "Ring",
    style: "Solitaire",
    shape: "Princess",
    salesPrice: "$870.90",
    plan: "LUXE",
    collection: "Engagement",
    createdAt: "January 1, 2023",
    lastUpdatedDate: "July 20, 2023",
    gender: "Female",
    active: <Switch size="sm" />,
  },
  {
    id: 2,
    productImg: "/images/products/product-ring.png",
    designNo: "1101-01PRI",
    category: "Ring",
    style: "Solitaire",
    shape: "Princess",
    salesPrice: "$870.90",
    plan: "LUXE",
    collection: "Engagement",
    createdAt: "January 1, 2023",
    lastUpdatedDate: "July 20, 2023",
    gender: "Female",
    active: <Switch size="sm" />,
  },
  {
    id: 3,
    productImg: "/images/products/product-ring.png",
    designNo: "1101-01PRI",
    category: "Ring",
    style: "Solitaire",
    shape: "Princess",
    salesPrice: "$870.90",
    plan: "LUXE",
    collection: "Engagement",
    createdAt: "January 1, 2023",
    lastUpdatedDate: "July 20, 2023",
    gender: "Female",
    active: <Switch size="sm" />,
  },
];

export const PRODUCT_LIST_DETAILS = [
  {
    id: 1,
    productImg: "/images/product-ring.png",
    designNo: "1101-01PRI",
    category: "Ring",
    style: "Solitaire",
    shape: "Princess",
    basePrice: "$870.90",
    plan: "LUXE",
    collection: "Engagement",
    createdAt: "January 1, 2023",
    lastUpdatedDate: "July 20, 2023",
    gender: "Female",
    active: <Switch size="sm" />,
    grossWeight: "2.694",
    netWeight: "2.4",
    diamondWeight: "1.47",
    diamondPiece: "28",
    metal: "$139.87",
    diamond: "$372",
    laborRate: "$14",
    laborPrice: "$35",
    totalPrice: "$547.87",
  },
];

export const PRODUCTS_IMAGES = [
  "/images/products/1.png",
  "/images/products/1.png",
  "/images/products/1.png",
  "/images/products/1.png",
  "/images/products/1.png",
  "/images/products/1.png",
  "/images/products/1.png",
  "/images/products/1.png",
  "/images/products/1.png",
  "/images/products/1.png",
  "/images/products/1.png"
];