import { Switch } from "@/components/common/ui/switch";

export const PRODUCT_LIST_DATA = [
  {
    id: 1,
    logo: "/images/brand-logo/plurk.png",
    name: "Necklaces",
    status: "Active",
    no_of_products: "45/50",
    budget_used: "33L",
    margin: "10%",
    last_updated: "2 min ago",
  },
  {
    id: 2,
    logo: "/images/brand-logo/disqus.png",
    name: "Bracelets",
    status: "Active",
    no_of_products: "35/55",
    budget_used: "33L",
    margin: "10%-12%",
    last_updated: "3 min ago",
  },
  {
    id: 3,
    logo: "/images/brand-logo/clara.png",
    name: "Rings",
    status: "Active",
    no_of_products: "30/57",
    budget_used: "32L",
    margin: "9%",
    last_updated: "5 min ago",
  },
  {
    id: 4,
    logo: "/images/brand-logo/vimeo.png",
    name: "Earrings",
    status: "Active",
    no_of_products: "30/35",
    budget_used: "25L",
    margin: "15%",
    last_updated: "1 min ago",
  },
  {
    id: 5,
    logo: "/images/brand-logo/vimeo.png",
    name: "Wedding Bands",
    status: "Active",
    no_of_products: "25/30",
    budget_used: "15L",
    margin: "7%",
    last_updated: "7 min ago",
  },
  {
    id: 6,
    logo: "/images/brand-logo/spring.png",
    name: "Mangalsutra",
    status: "Active",
    no_of_products: "26/40",
    budget_used: "33L",
    margin: "7%-10%",
    last_updated: "3 min ago",
  },
  {
    id: 7,
    logo: "/images/brand-logo/spring.png",
    name: "Pendants",
    status: "Inactive",
    no_of_products: "15/30",
    budget_used: "28L",
    margin: "11%",
    last_updated: "8 min ago",
  },
];

export const PRODUCT_MASTER_DATA = [
  {
    id: 1,
    productImg: "/images/products/product-ring.png",
    designNo: "1101-01PRI",
    category: "Ring",
    style: "Solitaire",
    shape: "Princess",
    salesPrice: "$870.90",
    plan: "LUXE",
    collection: "Engagement",
    createdAt: "January 1, 2023",
    lastUpdatedDate: "July 20, 2023",
    gender: "Female",
    active: <Switch size="sm" />,
  },
  {
    id: 2,
    productImg: "/images/products/product-ring.png",
    designNo: "1101-01PRI",
    category: "Ring",
    style: "Solitaire",
    shape: "Princess",
    salesPrice: "$870.90",
    plan: "LUXE",
    collection: "Engagement",
    createdAt: "January 1, 2023",
    lastUpdatedDate: "July 20, 2023",
    gender: "Female",
    active: <Switch size="sm" />,
  },
  {
    id: 3,
    productImg: "/images/products/product-ring.png",
    designNo: "1101-01PRI",
    category: "Ring",
    style: "Solitaire",
    shape: "Princess",
    salesPrice: "$870.90",
    plan: "LUXE",
    collection: "Engagement",
    createdAt: "January 1, 2023",
    lastUpdatedDate: "July 20, 2023",
    gender: "Female",
    active: <Switch size="sm" />,
  },
];

export const PRODUCT_LIST_DETAILS = [
  {
    id: 1,
    productImg: "/images/product-ring.png",
    designNo: "1101-01PRI",
    category: "Ring",
    style: "Solitaire",
    shape: "Princess",
    basePrice: "$870.90",
    plan: "LUXE",
    collection: "Engagement",
    createdAt: "January 1, 2023",
    lastUpdatedDate: "July 20, 2023",
    gender: "Female",
    active: <Switch size="sm" />,
    grossWeight: "2.694",
    netWeight: "2.4",
    diamondWeight: "1.47",
    diamondPiece: "28",
    metal: "$139.87",
    diamond: "$372",
    laborRate: "$14",
    laborPrice: "$35",
    totalPrice: "$547.87",
  },
];

export const PRODUCTS_IMAGES = [
  "/images/products/1.png",
  "/images/products/1.png",
  "/images/products/1.png",
  "/images/products/1.png",
  "/images/products/1.png",
  "/images/products/1.png",
  "/images/products/1.png",
  "/images/products/1.png",
  "/images/products/1.png",
  "/images/products/1.png",
  "/images/products/1.png",
];

export const BROWSE_PRODUCTS = [
  {
    id: "1101-01",
    title: "Engagement Ring",
    style: "Solitaire",
    collection: "Best Seller",
    category: "Sneakers",
    image: "/images/ring.png",
  },
  {
    id: "1101-01111",
    title: "Engagement",
    style: "Solitaire",
    collection: "Best Seller",
    category: "Sneakers",
    image: "/images/ring.png",
  },
];

export const FILTERS = [
  {
    label: "Style",
    key: "style",
    options: ["Show all", "Modern", "Vintage", "Classic"],
  },
  {
    label: "Shape",
    key: "shape",
    options: ["Show all", "Round", "Oval", "Princess"],
  },
  {
    label: "Price Range",
    key: "price",
    options: ["Show all", "₹0–10k", "₹10k–25k", "₹25k+"],
  },
];

export const PRODUCTS_DETAILS = [
  {
    id: 1,
    variantsimg: "/images/products/vector.svg",
    name: "Round",
    baseprice: "$850.45 $950.45",
    defaultmargin: "10%",
    sellingprice: "$1050",
    metal: ["#D6B34C", "#D9D9D9", "#D8A083", "#E8E8E8"],
    active: <Switch size="sm" />,
  },
  {
    id: 2,
    variantsimg: "/images/products/princess.svg",
    name: "Princess",
    baseprice: "$850.45 $950.45",
    defaultmargin: "10%",
    sellingprice: "$1050",
    metal: ["#D6B34C", "#D9D9D9", "#D8A083", "#E8E8E8"],
    active: <Switch size="sm" />,
  },
  {
    id: 3,
    variantsimg: "/images/products/oval.svg",
    name: "Round",
    baseprice: "$850.45 $950.45",
    defaultmargin: "10%",
    sellingprice: "$1050",
    metal: ["#D6B34C", "#D9D9D9", "#D8A083", "#E8E8E8"],
    active: <Switch size="sm" />,
  },
  {
    id: 4,
    variantsimg: "/images/products/cushion.svg",
    name: "Round",
    baseprice: "$850.45 $950.45",
    defaultmargin: "10%",
    sellingprice: "$1050",
    metal: ["#D6B34C", "#D9D9D9", "#D8A083", "#E8E8E8"],
    active: <Switch size="sm" />,
  },
  {
    id: 5,
    variantsimg: "/images/products/radiant.svg",
    name: "Round",
    baseprice: "$850.45 $950.45",
    defaultmargin: "10%",
    sellingprice: "$1050",
    metal: ["#D6B34C", "#D9D9D9", "#D8A083", "#E8E8E8"],
    active: <Switch size="sm" />,
  },
  {
    id: 6,
    variantsimg: "/images/products/pear.svg",
    name: "Round",
    baseprice: "$850.45 $950.45",
    defaultmargin: "10%",
    sellingprice: "$1050",
    metal: ["#D6B34C", "#D9D9D9", "#D8A083", "#E8E8E8"],
    active: <Switch size="sm" />,
  },
];

export const MANAGE_COLLECTION_DATA = [
  {
    id: 1,
    collection_name: "Diamond Rings",
    product_image: "/images/products/collection-ring.png",
    description: "Elegant diamond ring with gold finish",
    products: 12,
    created_at: "2025-09-15T10:30:00Z",
    is_active: true,
    status: 1,
  },
  {
    id: 2,
    collection_name: "Pearl Necklace",
    product_image: "/images/products/collection-necklace.png",
    description: "Classic pearl necklace with silver chain",
    products: 8,
    created_at: "2025-08-28T14:10:00Z",
    is_active: false,
    status: 0,
  },
  {
    id: 3,
    collection_name: "Rose Bracelet",
    product_image: "/images/products/collection-bracelet.png",
    description: "Rose gold bracelet with diamond charms",
    products: 5,
    created_at: "2025-07-22T08:45:00Z",
    is_active: true,
    status: 1,
  },
  {
    id: 4,
    collection_name: "Stud Earrings",
    product_image: "/images/products/collection-earrings.png",
    description: "Minimalist stud earrings set",
    products: 9,
    created_at: "2025-07-01T11:00:00Z",
    is_active: true,
    status: 1,
  },
  {
    id: 5,
    collection_name: "Platinum Chain",
    product_image: "/images/products/collection-chain.png",
    description: "Men’s platinum chain with modern design",
    products: 6,
    created_at: "2025-06-18T16:20:00Z",
    is_active: false,
    status: 0,
  },
];
