export const PRODUCTS_DATA = [
  {
    id: "1",
    title: "Radiant Solitaire Diamond Ring",
    image: "/images/ring.png",
    hoverImage: "/images/ring1-hover.jpg",
    diamondInfo: "1.2ct, VVS1, E Color",
    category: "Rings",
    collection: "Bridal Collection",
    designNumber: "RNG-2024-001",
    mrp: 125000,
    prp: 95000,
    srp: 112500,
    style: "Solitaire",
    diamondShape: "Round",
    metalOptions: ["18K White Gold", "18K Yellow Gold", "Platinum"],
  },
  {
    id: "2",
    title: "Classic Diamond Stud Earrings",
    image: "/images/products/pm3.png",
    hoverImage: "/images/earring1-hover.jpg",
    diamondInfo: "0.8ct Total, VS2, F Color",
    category: "Earrings",
    collection: "Classic Collection",
    designNumber: "ERG-2024-045",
    mrp: 68000,
    prp: 52000,
    srp: 61200,
    style: "Stud",
    diamondShape: "Round",
    metalOptions: ["18K White Gold", "18K Yellow Gold"],
  },

  {
    id: "3",
    title: "Classic Diamond Stud Earrings",
    image: "/images/products/pm5.png",
    hoverImage: "/images/earring1-hover.jpg",
    diamondInfo: "0.8ct Total, VS2, F Color",
    category: "Earrings",
    collection: "Classic Collection",
    designNumber: "ERG-2024-045",
    mrp: 68000,
    prp: 52000,
    srp: 61200,
    style: "Stud",
    diamondShape: "Round",
    metalOptions: ["18K White Gold", "18K Yellow Gold"],
  },

  {
    id: "4",
    title: "Classic Diamond Stud Earrings",
    image: "/images/products/pm2.png",
    hoverImage: "/images/earring1-hover.jpg",
    diamondInfo: "0.8ct Total, VS2, F Color",
    category: "Earrings",
    collection: "Classic Collection",
    designNumber: "ERG-2024-045",
    mrp: 68000,
    prp: 52000,
    srp: 61200,
    style: "Stud",
    diamondShape: "Round",
    metalOptions: ["18K White Gold", "18K Yellow Gold"],
  },
];
